package basisFx;

import basisFx.dataSource.DbSchema;

public class DbSchemaStudent extends DbSchema {
    public void create() {


        String faculty = "CREATE CACHED  TABLE IF NOT EXISTS Faculty ( "
                + "	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  "
                + "	name  VARCHAR(100), "
                + " UNIQUE  (name)"
                + ")";


        String studentsgroup = "CREATE CACHED  TABLE IF NOT EXISTS studentsgroup ( "
                + "	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  "
                + "	name  VARCHAR(100), "
                + "	FacultyId INTEGER   , "
                + " FOREIGN KEY (FacultyId) REFERENCES Faculty(id)  , "
                + " UNIQUE  (name)"
                + ")";


        String male = "CREATE CACHED  TABLE IF NOT EXISTS male ( "
                + "	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  "
                + "	name  VARCHAR(100), "
                + " UNIQUE  (name)"
                + ")";


        String student = "CREATE CACHED  TABLE IF NOT EXISTS student ( "
                + "	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  "
                + "	name  VARCHAR(100) ,"
                + "	city  VARCHAR(100) ,"
                + "	enterprise  VARCHAR(100) ,"
                + "	maleId INTEGER,  "
                + "	studentsgroupId INTEGER,  "
                + " birthday Date,   "
                 + " FOREIGN KEY (studentsgroupId) REFERENCES male(id)  , "
                 + " FOREIGN KEY (maleId) REFERENCES studentsgroup(id)  "
                + ")";




        String males = "insert into male (name) values ('м', 'ж')";








        init(
                faculty,
                male,
                studentsgroup,
                student,
                males
        );

    }
    }
